from pathlib import Path
import json
p=Path('/mnt/data/kaza_blog_update/src/data/pages.json')
pages=json.loads(p.read_text(encoding='utf-8'))
extra={
'kaza-namazi-nasil-kilinir':'''
<h2>Kaza namazını günlük hayata yerleştirme</h2><p>Kaza namazını kalıcı bir alışkanlığa dönüştürmek için onu mevcut bir davranışa bağlamak faydalıdır. Örneğin her farz namazdan sonra aynı vaktin bir kazasını kılmak, ayrıca hatırlatıcı kurmaya duyulan ihtiyacı azaltır. Bu yöntem herkes için zorunlu değildir; önemli olan düzenli uygulanabilen bir sistem kurmaktır. Sabahları zamanı dar olan kişi öğle ve yatsı sonrasında daha fazla kaza kılabilir. Çalışma düzeni değişken olan kişi günlük sayı yerine haftalık toplam belirleyebilir.</p><p>Bir namaz borcunun uzun görünmesi kişiyi başlamaktan alıkoymamalıdır. Hesaplama sonucu yalnızca mevcut durumu görünür kılar. İlk hedef, tüm borcu kısa sürede bitirmek değil, bugünden itibaren düzenli ilerlemektir. Beş dakikalık küçük bir rutin aylar içinde önemli bir toplam oluşturabilir.</p>
<h2>Kaza namazında okunan sureler ve dualar</h2><p>Kaza namazında, ilgili farz namazda okunan sure ve dualar okunur. Fâtiha, zamm-ı sûre, rükû ve secde tesbihleri ile oturuş duaları normal namaz düzenine göre yerine getirilir. Kişi yalnızca niyet kısmında bunun bir kaza namazı olduğunu belirler. Ezber konusunda eksiklik varsa önce namazın asgari geçerlilik şartlarını güvenilir bir ilmihal kaynağından öğrenmek, ardından ezberi geliştirmek gerekir.</p>
<h2>Birden fazla kaza namazı peş peşe kılınır mı?</h2><p>Uygun vakitte birden fazla kaza namazı peş peşe kılınabilir. Her namaz için ayrı niyet edilir ve her biri selamla tamamlanır. Uzun bloklar oluştururken dikkat dağınıklığı ve yorgunluk hesaba katılmalıdır. Örneğin on namazı tek oturumda kılmak yerine sabah beş, akşam beş şeklinde ikiye bölmek daha sürdürülebilir olabilir.</p>
''',
'kaza-namazi-ne-zaman-kilinir':'''
<h2>Vakit namazı ile kaza namazı arasında öncelik</h2><p>Yeni vaktin çıkmasına az kalmışsa öncelik o vaktin farzını vaktinde kılmaktır. Kaza planı hazırlanırken mevcut farz namazların gecikmesine yol açacak bir düzen kurulmamalıdır. Vakit genişse ve kişinin az sayıda kaza borcu varsa sıra hükümleri ayrıca gündeme gelebilir. Çok sayıda kaza borcu bulunan kişilerde ise günlük programın sürdürülebilirliği daha belirgin bir pratik ihtiyaçtır.</p><p>Örneğin akşam namazına yirmi dakika kalmış ve kişinin ikindi namazını henüz kılmamış olması hâlinde, önce mevcut ikindi farzının vaktinde eda edilmesi gerekir. Buna karşılık yatsıdan sonra geniş bir zaman varsa kişi planındaki kaza namazlarını kılabilir.</p>
<h2>Çalışanlar için zaman önerileri</h2><p>İş günlerinde sabah erken saat, öğle molası ve yatsı sonrası üç kısa pencere kullanılabilir. Her pencereye bir veya iki kaza eklemek günlük hedefi gün içine dağıtır. Tek bir uzun oturuma bağlı planlar, beklenmedik yoğunlukta tamamen aksayabilir. Dağıtılmış plan ise bir bölüm kaçsa bile diğer bölümlerin sürmesini sağlar.</p>
<h2>Hafta sonu yoğunlaştırılmış plan doğru mu?</h2><p>Hafta içi az, hafta sonu daha çok kılmak mümkündür; ancak yalnızca hafta sonuna güvenmek düzeni kırılgan hâle getirebilir. Daha dengeli model, hafta içi düşük bir minimum hedef ve hafta sonu ek hedef belirlemektir. Örneğin hafta içi günde üç, cumartesi ve pazar günde on vakitlik plan haftada 35 vakit eder.</p>
''',
'kaza-namazi-ne-zaman-kilinmaz':'''
<h2>Kerahat vakitlerini takvimden nasıl kontrol edebilirsiniz?</h2><p>Günlük namaz takviminde “güneş” saati, güneşin doğuşunu gösterir. Bu saate çok yakın bir dönemde namaza başlamamak gerekir. Öğle vaktinden hemen önceki zeval süresi takvimlerde ayrı bir satır olarak her zaman gösterilmez; bu nedenle öğleye birkaç dakika kala yeni bir kaza namazına başlamamak güvenli bir uygulamadır. Akşam vaktine çok yaklaşınca da güneşin batış safhası dikkate alınmalıdır.</p><p>Konum değiştiğinde saatler de değişir. İstanbul için uygun olan dakika aralığını Ankara, İzmir veya yurt dışı için aynen kullanmak doğru değildir. Telefonunuzdaki takvimin konum iznini ve seçili şehri kontrol edin.</p>
<h2>Kerahat vaktine yaklaşırken başlanmış namaz</h2><p>Namaza kerahat vakti girmeden önce başlanmış olması, namazın türüne ve vaktin niteliğine göre farklı hükümler doğurabilir. Özellikle güneşin batışına çok yakın dönemde bu ayrıntılar önem kazanır. Kişisel bir olay yaşandıysa “namaz geçerli mi?” sorusuna genel internet metniyle kesin cevap vermek yerine vakti, başlangıç anını ve namaz türünü belirterek din görevlisine danışmak gerekir.</p>
<h2>Kerahat vakti ile mekruh vakit aynı şey midir?</h2><p>Günlük dilde iki ifade çoğu zaman birbirinin yerine kullanılır. Fıkıh kaynaklarında ise hangi namazın hangi zaman aralığında kılınmasının yasak, tahrîmen mekruh veya tenzîhen mekruh olduğu daha ayrıntılı sınıflandırılabilir. Bu rehber, kullanıcıların temel güneş bağlantılı vakitleri fark etmesini amaçlar; mezhepsel tüm ayrıntıların yerine geçmez.</p>
''',
'kaza-namazi-niyeti':'''
<h2>Niyette “ilk” ve “son” ifadesi nasıl kullanılır?</h2><p>Çok sayıda sabah namazı borcu bulunan kişi, her seferinde “üzerimdeki ilk kazaya kalmış sabah namazının farzına” niyet edebilir. Bir namaz tamamlandığında sıradaki borç artık ilk hâline gelir. “Son” yöntemi de ters yönde aynı mantıkla kullanılabilir. İki yöntemi aynı plan içinde sürekli değiştirmek yerine birini seçmek takibi kolaylaştırır.</p>
<h2>Niyet ile hesaplama çizelgesi nasıl eşleştirilir?</h2><p>Çizelgede tarihleri tek tek bilmiyorsanız vakit türlerini ayrı sütunlarda tutun. Örneğin sabah hanesinde 320, öğle hanesinde 315 kalan namaz bulunabilir. Her namazda ilgili vaktin ilk kazasına niyet edip tamamlanan toplamı bir azaltabilirsiniz. Böylece niyet yöntemi ile sayısal takip arasında tutarlılık sağlanır.</p>
<h2>Niyet sırasında yapılan dil hataları namazı bozar mı?</h2><p>Kişinin dili sürçebilir veya cümleyi eksik söyleyebilir. Asıl belirleyici kalben hangi namazı kılmak istediğidir. Buna rağmen tamamen farklı bir namazı kastetmek ya da hangi namazı kıldığını hiç belirlememek ayrı bir durumdur. Şüphe duyulan kişisel uygulamalarda mezhebe uygun fetva alınmalıdır.</p>
<h2>Kaza namazına başlarken kamet gerekir mi?</h2><p>Tek başına kaza namazı kılarken ezan ve kamet konusu mezhep ve uygulama ayrıntısı içerir. Namazın geçerliliği için kullanıcıların asıl odaklanması gereken husus niyet, taharet, kıble, kıraat ve namazın rükünleridir. Kametle ilgili tercih için güvenilir ilmihal kaynağı izlenebilir.</p>
''',
'kaza-namazi-kac-rekat':'''
<h2>Vakit sayısı ile rekât sayısı arasındaki fark</h2><p>Hesaplama sonuçlarında iki ayrı toplam görürsünüz. “Vakit”, tamamlanması gereken namaz adedidir; “rekât” ise bu namazların içindeki toplam rekât sayısıdır. Bir sabah kazası da bir vakittir, bir öğle kazası da bir vakittir; ancak sabah iki, öğle dört rekâttır. Bu nedenle 100 vakit her zaman aynı rekât toplamına karşılık gelmez.</p><p>Plan oluştururken günlük hedefi vakit üzerinden belirlemek daha kolaydır. Fiziksel zaman ihtiyacını tahmin etmek için ise hangi vakitlerin ağırlıklı olduğuna bakmak gerekir.</p>
<h2>Yıllık hesaplarda neden yaklaşık ifadesi kullanılır?</h2><p>Bir takvim yılı bazen 365, bazen 366 gündür. On yıllık dönemde iki veya üç artık yıl bulunabilir. Ayrıca başlangıç ve bitiş tarihinin yılın hangi gününe denk geldiği sonucu etkiler. Bu nedenle “10 yıl = tam 3.650 gün” ifadesi yalnızca kaba tahmindir. Tarih aralığı yöntemi gerçek gün sayısını daha doğru verir.</p>
<h2>Seferî namazların rekât hesabı</h2><p>Yolculuk hâlinde kazaya kalan namazların mukimken nasıl kaza edileceği özel bir fıkıh konusudur. Diyanet açıklamasında geçmiş namazların kazaya nasıl kaldıysa o şekilde kılınacağı belirtilir. Uzun süreli seyahat, askerlik veya şehir dışı çalışma dönemleriniz varsa standart 17 rekât çarpanını doğrudan uygulamadan önce bu dönemleri ayrı değerlendirin.</p>
<h2>Rekât hesabı neden tek başına yeterli değildir?</h2><p>Toplam rekât büyük bir sayı verdiği için motivasyonu azaltabilir. 60.000 rekât yerine 18.000 vakit veya günde beş vakitlik plan daha yönetilebilir görünür. Bu yüzden sonuç ekranında hem bilgi amaçlı rekât toplamı hem de eyleme dönük vakit sayısı birlikte sunulur.</p>
''',
'kaza-namazi-nasil-hesaplanir':'''
<h2>Kısmen namaz kılınan dönem nasıl hesaplanır?</h2><p>Bir dönemde beş vaktin tamamı değil, yalnızca bazıları kılındıysa gün bazlı tek düşüm yeterli olmayabilir. Örneğin bir yıl boyunca yalnızca sabah ve yatsı namazlarını düzenli kıldıysanız, o yılın sabah ve yatsı borcu oluşmazken öğle, ikindi ve akşam için borç oluşur. Böyle bir durumda her vakti ayrı hesaplamak daha doğrudur.</p><p>Basit yöntem olarak toplam gün sayısını belirleyip seçili vakitleri işaretleyebilirsiniz. Daha ayrıntılı takipte ise sabah, öğle, ikindi, akşam ve yatsı için ayrı kalan toplamlar tutulur.</p>
<h2>Yuvarlama nasıl yapılmalı?</h2><p>Kesin gün bilinmiyorsa sonucu aşağı veya yukarı yuvarlama tercihi kişisel ihtiyata bağlıdır. Aracın amacı eksik borcu olduğundan az göstermek değil, açıklanabilir bir tahmin sunmaktır. Tarih aralığından gelen ondalıklı sonuç olmaz; yıl sayısından yapılan ortalama hesapta ise en yakın tam güne yuvarlama uygulanabilir.</p>
<h2>Birden fazla dönem nasıl birleştirilir?</h2><p>Namazın düzensiz olduğu hayat dönemlerini ayrı ayrı hesaplamak hatayı azaltır. Örneğin 2015–2018 hiç kılınmayan dönem, 2018–2020 kısmen kılınan dönem ve 2020 sonrası düzenli dönem ayrı satırlarda ele alınabilir. Her dönemin eksik gün veya vakit toplamı bulunduktan sonra sonuçlar birleştirilir.</p>
<h2>Hesabı ne sıklıkla güncellemelisiniz?</h2><p>Başlangıç hesabını yaptıktan sonra her gün tekrar hesaplamaya gerek yoktur. Haftalık çizelgeyle tamamlanan vakitleri takip edin ve ay sonunda kalan toplamı güncelleyin. Yeni bir eski dönem hatırlarsanız veya muafiyet hesabınız değişirse başlangıç değerini revize edebilirsiniz.</p>
''',
'kadinlar-icin-kaza-namazi-hesaplama':'''
<h2>Hayız günleri için ortalama nasıl bulunur?</h2><p>Geçmiş yılların tamamını tek tek hatırlamak mümkün olmayabilir. Düzenli döngüsü olan kişi, ortalama hayız gününü ve yıldaki yaklaşık dönem sayısını kullanabilir. Örneğin ortalama altı gün ve yılda on iki dönem, yılda yaklaşık 72 gün eder. Bu sayı kişisel kayda dayanmıyorsa “tahmini” olarak not edilmelidir.</p><p>Döngü uzun yıllar boyunca değiştiyse tek ortalama yerine dönemlere ayırmak daha doğrudur. Örneğin ergenliğin ilk yılları, doğum öncesi dönem ve doğum sonrası dönem ayrı hesaplanabilir.</p>
<h2>Gebelik döneminde hesaplama</h2><p>Gebelik tek başına namaz yükümlülüğünü kaldıran bir dönem değildir. Bu nedenle gebelik günlerinin tamamı muafiyet olarak düşülmez. Ancak doğum sonrası lohusalık dönemi ve gebelik sırasında ortaya çıkan özel sağlık durumları ayrıca değerlendirilir. Sağlık nedeniyle kılınamayan namazlarla ilgili hüküm için kişisel danışmanlık gerekir.</p>
<h2>İstihâze günleri neden otomatik düşülmez?</h2><p>İstihâze, hayız ve lohusalık dışındaki kanama olarak değerlendirilir ve namaz yükümlülüğü devam eder. Hangi günlerin hayız, hangilerinin istihâze olduğu mezhebin ölçülerine ve kişinin düzenine göre belirlenir. Tüm kanamalı günleri doğrudan muafiyet saymak kaza borcunu eksik gösterebilir.</p>
<h2>Kadınlara özel hesapta gizlilik ve veri minimizasyonu</h2><p>Bu hesap için isim, e-posta veya sağlık kaydı gerekmez. Kullanıcı yalnızca toplam muafiyet gününü girebilir. Ayrıntılı döngü tarihlerini siteye yüklemek zorunda değildir. Kişisel not tutmak isteyenler cihazlarında veya basılı çizelgede anonim bir kayıt kullanabilir.</p>
''',
'erkekler-icin-kaza-namazi-hesaplama':'''
<h2>Kısmi ibadet dönemleri nasıl ele alınır?</h2><p>Bir erkek kullanıcı yıllarca tamamen namazsız kalmamış, cuma günleri veya bazı vakitlerde namaz kılmış olabilir. Hesabı doğru yapmak için bu dönemleri “tam borç” kabul etmek yerine mümkün olduğunca vakit bazında ayırmak gerekir. Örneğin yalnızca sabah namazının düzenli kılındığı iki yıllık dönemde sabah borcu düşülür, diğer dört vakit borçta kalır.</p>
<h2>Askerlik, seyahat ve seferîlik</h2><p>Uzun yolculuk veya askerlik dönemlerinde seferî olarak kazaya kalan dört rekâtlı namazların hesabı standart mukim hesaptan farklı olabilir. Bu dönemler önemli bir toplam oluşturuyorsa ayrı not alın ve mezhebinize göre nasıl kaza edileceğini öğrenin. Sadece yıl sayısını 17 rekâtla çarpmak bu özel dönemi doğru temsil etmeyebilir.</p>
<h2>Çalışma hayatında sürdürülebilir plan</h2><p>Vardiyalı çalışanlar için her farzdan sonra bir kaza modeli her gün aynı biçimde uygulanamayabilir. Bunun yerine haftalık hedef, izin gününde ek blok ve iş gününde minimum hedef birlikte kullanılabilir. Örneğin iş günlerinde iki, izin günlerinde on vakitlik plan haftalık ortalamayı korur.</p>
<h2>Hesap sonucunu nasıl doğrulayabilirsiniz?</h2><p>Önce yıl yöntemiyle hızlı bir sonuç alın, ardından hatırladığınız tarihleri kullanarak tarih aralığı hesabıyla karşılaştırın. İki sonuç arasında büyük fark varsa namaz kılınan dönemleri veya başlangıç yaşını tekrar kontrol edin. Hesabı bir aile büyüğüyle geçmiş tarihler üzerinden gözden geçirmek de belirsizliği azaltabilir.</p>
''',
'kaza-namazi-cizelgesi':'''
<h2>Aylık özet bölümü ekleyin</h2><p>Günlük çizelgenin sonunda aylık toplam, günlük ortalama ve kalan borç için üç alan bulunması ilerlemeyi görünür kılar. Örneğin ay içinde 120 vakit tamamlandıysa günlük ortalama yaklaşık 3,9 vakittir. Gelecek ayın hedefi bu gerçek ortalamaya göre belirlenebilir.</p>
<h2>Renk ve işaret sistemi nasıl olmalı?</h2><p>Basılı çizelgede tamamlanan vakit için tik, planlanıp tamamlanmayan için boş daire, sonradan telafi edilen için farklı bir işaret kullanabilirsiniz. Çok fazla renk veya karmaşık kod, takibi zorlaştırır. Dijital çizelgede de yalnızca tamamlandı ve bekliyor durumları çoğu kullanıcı için yeterlidir.</p>
<h2>Çizelge borcun kesinliğini garanti eder mi?</h2><p>Çizelge, başlangıçta hesaplanan tahmini borç üzerinden ilerler. Başlangıç hesabı değişirse çizelgedeki kalan toplam da güncellenmelidir. Yeni bir muafiyet dönemi hatırlandığında veya eski bir namaz kılma dönemi tespit edildiğinde düzeltme yapılabilir.</p>
<h2>İki farklı çizelge yöntemi</h2><p><strong>Azalan toplam yöntemi</strong>, her tamamlanan vakitte kalan borcu bir azaltır. <strong>Birikimli yöntem</strong> ise yalnızca bugüne kadar tamamlanan toplamı tutar. Azalan yöntem hedefe kalan mesafeyi, birikimli yöntem ise başarıyı daha görünür gösterir. İkisini aynı sayfada kullanmak en kapsamlı çözümdür.</p>
''',
'kaza-namazi-bitirme-plani':'''
<h2>Planın gerçek hızını ölçme</h2><p>İlk ay sonunda planlanan hedef ile gerçekleşen ortalamayı karşılaştırın. Günde 10 hedefleyip ortalama 4,5 tamamladıysanız bitiş tarihini 10 üzerinden değil 4,5 üzerinden güncelleyin. Gerçek veriye dayalı plan, gereksiz hayal kırıklığını önler.</p>
<h2>Kademeli hedef artırma</h2><p>İlk iki hafta günde bir, sonraki iki hafta günde üç, ikinci aydan itibaren günde beş vakit modeline geçilebilir. Kademeli artış özellikle uzun süredir düzenli ibadet alışkanlığı olmayan kişilerde daha uygulanabilir olabilir. Hedef artışı, mevcut farzların düzenini bozuyorsa geri çekilmelidir.</p>
<h2>Molalar ve özel dönemler</h2><p>Hastalık, seyahat, iş yoğunluğu veya aile sorumlulukları planın hızını değiştirebilir. Bu dönemleri başarısızlık olarak görmek yerine hedefi geçici olarak azaltın. Ay sonunda gerçek ortalamayı hesaplayıp yeni bitiş tarihi oluşturun.</p>
<h2>Vakit bazlı dengeli bitirme</h2><p>Yalnızca en kısa olduğu için sabah kazalarını bitirip diğer vakitleri ertelemek toplam vakit sayısını düşürse de dengeli bir plan sunmayabilir. Her vakitten birer tane kılmak veya haftalık dağılım yapmak tüm namaz türlerinin birlikte azalmasını sağlar. Kişisel sıra ve niyet uygulamanız için mezhep bilginizi dikkate alın.</p>
'''
}
for x in pages:
    if x['slug'] in extra:
        marker='<section class="article-faq">'
        if marker in x['content_html']:
            x['content_html']=x['content_html'].replace(marker,extra[x['slug']]+marker,1)
        else:
            x['content_html']+=extra[x['slug']]
p.write_text(json.dumps(pages,ensure_ascii=False,indent=2),encoding='utf-8')
