from pathlib import Path
import json

ROOT=Path('/mnt/data/kaza_blog_update')
DATA=ROOT/'src/data/pages.json'

SRC={
'delil':'https://kurul.diyanet.gov.tr/tr/fetva/kaza-namazinin-delili-nedir/0193c42d-52a0-7585-1c39-e6137aac81ec',
'hangi':'https://kurul.diyanet.gov.tr/tr/fetva/hangi-namazlar-kaza-edilir/0193c42d-5327-7459-64e7-211baaf5ab8c',
'vakit':'https://kurul.diyanet.gov.tr/tr/fetva/kaza-namazi-kilinirken-ezan-okunursa-kaza-namazina-devam/0193c42d-5390-7374-9846-22276ba1aa19',
'niyet':'https://kurul.diyanet.gov.tr/soru/kaza-namazina-nasil-niyet-edilir/0193c42d-52e1-7e5a-b12d-2741abb870a6',
'sira':'https://kurul.diyanet.gov.tr/tr/fetva/kaza-edilecek-namazlar-arasinda-bir-sira-takip-etmek-sart/0193c42d-53a7-7f75-e52e-a68b829b3393',
'yeni':'https://kurul.diyanet.gov.tr/tr/fetva/kazaya-kalan-namaz-yeni-vakit-girdiginde-o-vaktin/0193c42d-53bc-7458-883d-614f98fe00e0',
'kadin':'https://kurul.diyanet.gov.tr/tr/fetva/kadinlar-adet-ve-lohusalik-hallerinde-oruc-tutabilirler-mi/0193c42d-73c5-7492-2991-feb663fcc9ec',
'adet':'https://kurul.diyanet.gov.tr/tr/fetva/duzenli-olarak-uc-gunden-az-ya-da-on-gunden-fazla-kanamasi/0193c42d-4bc3-7336-8bf6-117b4978b02d',
'sunnet':'https://kurul.diyanet.gov.tr/tr/fetva/kaza-namazi-borcu-olan-kimse-sunnet-namazlari-kilabilir-mi/0193c42d-5313-7269-a0b5-a1d2446d1e15',
}

def box(title,text,kind='note'):
    return f'<div class="content-box {kind}"><strong>{title}</strong><p>{text}</p></div>'

def faq(items):
    return '<section class="article-faq"><h2>Sık sorulan sorular</h2>'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</section>'

def sources(items):
    return '<section class="article-sources"><h2>Kaynaklar ve önemli not</h2><ul>'+''.join(f'<li><a href="{url}" target="_blank" rel="noopener noreferrer">{label}</a></li>' for label,url in items)+'</ul><p>Bu rehber genel bilgilendirme ve planlama amacıyla hazırlanmıştır. Kişisel durumunuz, mezhebiniz veya özel bir ibadet meselesi için yetkin bir din görevlisine danışmanız uygun olur.</p></section>'

common_toc=lambda links:'<nav class="article-toc" aria-label="İçindekiler"><strong>İçindekiler</strong><ol>'+''.join(f'<li><a href="#{i}">{t}</a></li>' for i,t in links)+'</ol></nav>'

articles={}

articles['kaza-namazi-nasil-kilinir']=f'''
{common_toc([('kisa-cevap','Kısa cevap'),('hazirlik','Hazırlık'),('adimlar','Adım adım kılınışı'),('vakitler','Vakitlere göre rekâtlar'),('niyet','Niyet'),('sira','Sıra ve planlama'),('hatalar','Sık yapılan hatalar')])}
<h2 id="kisa-cevap">Kaza namazı nasıl kılınır? Kısa cevap</h2>
<p>Kaza namazı, kazası kılınacak vaktin farz namazı esas alınarak kılınır. Sabah namazının farzı iki, öğle dört, ikindi dört, akşam üç ve yatsı dört rekâttır. Kişi hangi vaktin kazasını kıldığını niyetinde belirler; namazın kıyam, kıraat, rükû ve secde düzeni ilgili farz namazla aynıdır.</p>
{box('Önemli ayrım','Kaza namazı, kaçırılan farz namazın yerine kılınır. Hanefî uygulamasında vitir namazı da ayrıca kaza edilir. Sünnetlerin kazası ise aynı kapsamda değerlendirilmez; sabah namazının aynı gün öğle vaktinden önce kazası gibi özel durumlar ayrıca ele alınır.','info')}
<h2 id="hazirlik">Kaza namazına başlamadan önce</h2>
<p>Kaza namazı da diğer namazlar gibi abdest, kıbleye yönelme, örtünme, necasetten temizlik ve namaz vaktinin uygunluğu gibi genel şartlara bağlıdır. Önce hangi vaktin kazasını kılacağınızı belirleyin. Çok sayıda borcunuz varsa bugün yalnızca sürdürülebilir bir başlangıç yapmak, kısa sürede yorulacağınız yüksek bir hedef koymaktan daha faydalıdır.</p>
<ul><li>Abdestinizi ve namaz için gerekli şartları tamamlayın.</li><li>Kılacağınız vaktin sabah, öğle, ikindi, akşam veya yatsı olduğunu belirleyin.</li><li>Kalben o vaktin farz kazasına niyet edin.</li><li>İlgili farz namazın rekât sayısına göre namazı kılın.</li><li>Bitirdiğiniz vakti çizelgenize işleyin.</li></ul>
<h2 id="adimlar">Kaza namazı adım adım nasıl kılınır?</h2>
<p>Uygulama bakımından kaza namazı ile vaktinde kılınan farz namazın temel kılınış biçimi aynıdır. Fark, niyetin kazaya kalan namaza yönelik olmasıdır. Örneğin öğle namazının kazası dört rekât farz olarak kılınır.</p>
<ol><li><strong>Niyet:</strong> Hangi vaktin kazasını kıldığınızı kalben belirleyin.</li><li><strong>İftitah tekbiri:</strong> “Allahu ekber” diyerek namaza başlayın.</li><li><strong>Kıyam ve kıraat:</strong> İlgili farz namazdaki düzene göre kıraat yapın.</li><li><strong>Rükû ve secdeler:</strong> Her rekâtta normal namaz düzenini takip edin.</li><li><strong>Oturma ve selam:</strong> Rekât sayısına uygun oturuşları tamamlayıp selam verin.</li></ol>
<h2 id="vakitler">Vakitlere göre kaza namazı kaç rekâttır?</h2>
<div class="table-wrap"><table><thead><tr><th>Vakit</th><th>Kaza edilen bölüm</th><th>Rekât</th></tr></thead><tbody><tr><td>Sabah</td><td>Farz</td><td>2</td></tr><tr><td>Öğle</td><td>Farz</td><td>4</td></tr><tr><td>İkindi</td><td>Farz</td><td>4</td></tr><tr><td>Akşam</td><td>Farz</td><td>3</td></tr><tr><td>Yatsı</td><td>Farz</td><td>4</td></tr><tr><td>Vitir</td><td>Hanefî uygulamasında vacip</td><td>3</td></tr></tbody></table></div>
<p>Beş farz vaktin günlük toplamı 17 rekâttır. Hesaplama aracında vitri seçerseniz toplam ayrıca artar. Seferî iken kazaya kalan namazların nasıl kaza edileceği gibi özel durumlar için kişisel hüküm sorulmalıdır.</p>
<h2 id="niyet">Kaza namazına nasıl niyet edilir?</h2>
<p>Niyetin özü kalbin hangi namazı kıldığını bilmesidir. Belirli bir tarihteki sabah namazının kazasını biliyorsanız buna niyet edebilirsiniz. Tarihi bilinmeyen çok sayıda namaz için “kazaya kalan ilk sabah namazının farzına” veya “son sabah namazının farzına” şeklinde bir belirleme kullanılabilir. Kesin bir Türkçe cümleyi ezberlemek şart değildir.</p>
<h2 id="sira">Kaza namazlarında sıra ve günlük plan</h2>
<p>Kaza namazı sayısı az olan kişilerde vakitler arasındaki sıra konusu fıkıhta ayrıca değerlendirilir. Çok sayıda kaza borcu olan bir kişi ise pratik bir sistem kurabilir: her farzdan sonra aynı vaktin bir kazasını kılmak, sabah-akşam sabit bir blok ayırmak veya günlük toplam hedef belirlemek bunlardan bazılarıdır.</p>
<div class="table-wrap"><table><thead><tr><th>Plan</th><th>Uygulama</th><th>Kime uygun?</th></tr></thead><tbody><tr><td>Günde 1 vakit</td><td>Her gün sabit bir kaza</td><td>Yeni başlayanlar</td></tr><tr><td>Günde 5 vakit</td><td>Her farzdan sonra bir kaza</td><td>Dengeli tempo isteyenler</td></tr><tr><td>Günde 10 vakit</td><td>Sabah ve akşam blokları</td><td>Daha yüksek tempo sürdürebilenler</td></tr></tbody></table></div>
<h2 id="hatalar">Sık yapılan hatalar</h2>
<ul><li>İlk gün çok yüksek hedef koyup kısa sürede planı bırakmak.</li><li>Hangi vaktin kazasının kılındığını niyette belirlememek.</li><li>Farz ve sünneti tek niyetle birlikte kılmaya çalışmak.</li><li>Kerahat vakitlerini dikkate almamak.</li><li>Yaklaşık hesabı kesin ve tartışmasız bir sayı gibi kabul etmek.</li></ul>
{faq([('Kaza namazında sadece farz mı kılınır?','Genel hesapta beş vakit namazın farzları esas alınır. Hanefî uygulamasında vitir de kaza edilir. Sünnetlerle ilgili bazı özel durumlar bulunduğundan ayrıntılı hüküm için kaynaklara başvurulmalıdır.'),('Bir günde birden fazla kaza namazı kılınabilir mi?','Evet. Kerahat vakitleri dışında kişinin gücüne ve planına göre birden fazla kaza namazı kılınabilir.'),('Kaza namazı sesli mi okunur?','Kıraatın sesli veya sessiz olması, namazın türüne ve kişinin tek başına ya da cemaatle kılmasına göre değerlendirilir. Uygulamada mezhebinize uygun ilmihal bilgisine başvurun.'),('Kaza namazı cemaatle kılınabilir mi?','Aynı vaktin kazasına niyet edilmesi şartıyla cemaatle kılınabileceğine ilişkin Diyanet açıklaması bulunmaktadır.')])}
{sources([('Diyanet: Kaza namazının delili ve hangi namazların kaza edildiği',SRC['delil']),('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi']),('Diyanet: Kaza namazına niyet',SRC['niyet']),('Diyanet: Kaza namazlarında sıra',SRC['sira'])])}
'''

articles['kaza-namazi-ne-zaman-kilinir']=f'''
{common_toc([('kisa','Kısa cevap'),('uygun','Uygun zamanlar'),('farz-sonrasi','Farzlardan sonra'),('gece','Gece ve sabah'),('plan','Plan örnekleri'),('ezan','Ezan okunurken')])}
<h2 id="kisa">Kaza namazı ne zaman kılınır? Kısa cevap</h2><p>Kaza namazı için tek bir özel saat yoktur. Kerahat vakitleri dışında günün uygun zamanlarında kılınabilir. Kişi kaza namazını farz namazlardan önce veya sonra, gece saatlerinde ya da günlük programında ayırdığı sabit bir zaman diliminde kılabilir.</p>
<h2 id="uygun">Kaza namazı için uygun zamanlar</h2><p>En doğru zaman, namaz kılmanın yasak veya mekruh kabul edildiği kısa zaman aralıklarının dışında kalan ve düzenli devam edebileceğiniz zamandır. Diyanet açıklamalarında da kaza namazları için belli bir vakit bulunmadığı, kerahat vakitleri dışında kılınabileceği belirtilir.</p>
<ul><li>Farz namazlardan sonra</li><li>Gece yatmadan önce</li><li>Sabah güneş doğup kerahat vakti çıktıktan sonra</li><li>Öğle veya ikindi öncesinde uygun bir zaman diliminde</li><li>Hafta sonu daha uzun ibadet bloklarında</li></ul>
<h2 id="farz-sonrasi">Her farz namazdan sonra kaza namazı kılınır mı?</h2><p>Pratik planlardan biri, her farzdan sonra bir kaza namazı kılmaktır. Böylece günlük beş vakitlik bir hedef doğal biçimde mevcut ibadet düzenine bağlanır. Ancak yeni vakit namazını kaçıracak kadar gecikmemek ve kerahat vakitlerini gözetmek gerekir.</p>
{box('Planlama önerisi','Önce vaktin farzını güvence altına alın. Ardından müsaitseniz bir kaza namazı ekleyin. Kaza planı, mevcut namazların vaktinde kılınmasını zorlaştırmamalıdır.','info')}
<h2 id="gece">Gece veya sabah kaza namazı kılınabilir mi?</h2><p>Gece saatleri, sessizlik ve düzen açısından birçok kişi için uygundur. Sabah ise güneş doğarken ve hemen sonrasındaki kerahat süresi dikkate alınmalıdır. Güneş doğduktan sonra namaz kılmanın uygun olduğu vaktin başlamasını beklemek gerekir.</p>
<h2 id="plan">Günlük zaman planı örnekleri</h2><div class="table-wrap"><table><thead><tr><th>Model</th><th>Zaman</th><th>Günlük toplam</th></tr></thead><tbody><tr><td>Başlangıç planı</td><td>Yatsıdan sonra</td><td>1 vakit</td></tr><tr><td>Dengeli plan</td><td>Her farzdan sonra</td><td>5 vakit</td></tr><tr><td>İki bloklu plan</td><td>Sabah 5 + akşam 5</td><td>10 vakit</td></tr><tr><td>Haftalık plan</td><td>Hafta içi 3, hafta sonu 10</td><td>Haftalık ortalama</td></tr></tbody></table></div>
<h2 id="ezan">Kaza namazı kılarken ezan okunursa ne olur?</h2><p>Kaza namazı sırasında yeni bir vaktin ezanının okunması, başlanmış kaza namazını bozmaz. Namaz tamamlanabilir. Bununla birlikte yeni vaktin farzını vaktinde kılmak için programınızı buna göre ayarlamanız gerekir.</p>
{faq([('Yatsıdan sonra kaza namazı kılınır mı?','Evet, uygun şartlarda yatsıdan sonra kaza namazı kılınabilir.'),('Sabah namazından sonra kaza kılınır mı?','Güneşin doğuşuyla bağlantılı kerahat vakti dikkate alınmalıdır. Mezhebinize uygun ayrıntılı zaman bilgisini yerel namaz vakitleri ve ilmihal kaynağından kontrol edin.'),('İkindi namazından sonra kaza kılınır mı?','Güneşin batışına yaklaşan kerahat vakti nedeniyle ayrıntı önemlidir. Vaktin uygun kısmında ve mezhebinize göre hareket edin.'),('Kaza namazı için en iyi saat hangisidir?','Dinî açıdan tek bir “en iyi saat” belirlemek yerine kerahat vakitlerinden kaçınmak ve sürdürülebilir bir düzen seçmek daha uygundur.')])}
{sources([('Diyanet: Kaza namazı için belli bir vakit var mı?',SRC['vakit']),('Diyanet: Yeni vakit girdiğinde kaza namazının sırası',SRC['yeni'])])}
'''

articles['kaza-namazi-ne-zaman-kilinmaz']=f'''
{common_toc([('kisa','Kısa cevap'),('uc-vakit','Üç temel kerahat vakti'),('sabah','Sabah sonrası'),('ikindi','İkindi sonrası'),('kontrol','Pratik kontrol')])}
<h2 id="kisa">Kaza namazı ne zaman kılınmaz? Kısa cevap</h2><p>Kaza namazı, güneş doğarken, güneş tam tepe noktasındayken ve güneş batarken kılınmaz. Sabah ve ikindi namazlarından sonraki dönemlerde ise hükmün ayrıntısı namazın türüne ve mezhebe göre değişebilir. Bu nedenle özellikle güneşin doğuş ve batışına yakın zamanlardan kaçınmak güvenli bir uygulamadır.</p>
<h2 id="uc-vakit">Üç temel kerahat vakti</h2><div class="table-wrap"><table><thead><tr><th>Zaman</th><th>Genel açıklama</th><th>Ne yapılmalı?</th></tr></thead><tbody><tr><td>Güneş doğarken</td><td>Güneşin ufuktan yükseldiği kısa süre</td><td>Namaz için uygun vaktin başlamasını bekleyin</td></tr><tr><td>Güneş tepedeyken</td><td>Öğle vaktinden hemen önceki zeval anı</td><td>Öğle vaktinin girmesini bekleyin</td></tr><tr><td>Güneş batarken</td><td>Güneşin batışına çok yakın süre</td><td>Akşam vaktinin girmesini bekleyin</td></tr></tbody></table></div>
<p>Bu süreler sabit dakika olarak her gün aynı değildir; bulunduğunuz yer ve tarihe göre değişir. Namaz vakti uygulamalarında verilen güneş ve öğle bilgilerini kullanın.</p>
<h2 id="sabah">Sabah namazından sonra kaza namazı</h2><p>Sabah namazının farzından güneş doğuncaya kadar nafile namazlarla ilgili sınırlamalar bulunur. Kaza namazının hükmü mezhepsel ayrıntı içerdiğinden, güneşin doğuşuna yaklaşılmışsa beklemek daha güvenlidir. Güneş doğduktan sonra da kerahat süresinin çıkması beklenir.</p>
<h2 id="ikindi">İkindi namazından sonra kaza namazı</h2><p>İkindi namazından güneş batıncaya kadar olan sürede de ayrıntılı hükümler vardır. Özellikle güneşin sararıp batmaya yaklaştığı son bölümde kaza namazına başlanmamalıdır. Önceden başlanmış namaz veya o günün ikindi farzı gibi özel durumlar ayrıca değerlendirilir.</p>
{box('Neden dakika vermiyoruz?','Kerahat süresi coğrafi konuma, tarihe ve kullanılan fıkhî ölçüye göre değişebilir. “Güneşten tam 40 dakika sonra” gibi her yer ve gün için geçerli tek bir sayı vermek yanıltıcı olabilir.','warning')}
<h2 id="kontrol">Pratik kontrol listesi</h2><ul><li>Güneş doğuyor mu veya yeni doğdu mu?</li><li>Öğle vaktinin girmesine yalnızca çok kısa bir süre mi kaldı?</li><li>Güneş batmaya çok mu yaklaştı?</li><li>Yerel namaz vakitleri çizelgesini kontrol ettiniz mi?</li><li>Mezhebinizin sabah ve ikindi sonrasındaki ayrıntılı hükmünü biliyor musunuz?</li></ul>
{faq([('Kerahat vaktinde yanlışlıkla kaza namazı kılınırsa ne yapılır?','Bu durum namazın başladığı an, vaktin niteliği ve mezhebe göre değerlendirilir. Kişisel hüküm için din görevlisine danışın.'),('Öğle ezanından hemen önce kaza namazı kılınır mı?','Güneşin tepe noktasında olduğu zeval anından kaçınılmalıdır. Vaktin çok yaklaştığı durumda öğle vaktinin girmesini beklemek daha güvenlidir.'),('Güneş doğduktan kaç dakika sonra kılınabilir?','Tek bir sabit dakika bütün şehir ve tarihler için geçerli değildir. Yerel güneş vaktini ve güvenilir takvim bilgisini esas alın.'),('Gece kerahat vakti var mı?','Gece, bu üç temel güneş bağlantılı kerahat vaktinin dışında kalır; diğer namaz ve vakit hükümleri ayrıca gözetilir.')])}
{sources([('Diyanet: Kerahat vakitleri ve kaza namazı',SRC['vakit'])])}
'''

articles['kaza-namazi-niyeti']=f'''
{common_toc([('kisa','Kısa cevap'),('ornekler','Niyet örnekleri'),('bilinmeyen','Tarihi bilinmeyen namazlar'),('kalp','Kalben niyet'),('yanlislar','Sık karıştırılanlar')])}
<h2 id="kisa">Kaza namazına nasıl niyet edilir? Kısa cevap</h2><p>Kaza namazında niyet, hangi namazın kazasının kılındığını kalben belirlemektir. “Niyet ettim Allah rızası için kazaya kalan sabah namazının farzını kılmaya” denebilir. Çok sayıda ve tarihi bilinmeyen borçlarda “ilk” veya “son” kazaya kalan vakit belirlenebilir.</p>
<h2 id="ornekler">Vakitlere göre niyet örnekleri</h2><div class="table-wrap"><table><thead><tr><th>Vakit</th><th>Örnek niyet</th></tr></thead><tbody><tr><td>Sabah</td><td>Niyet ettim Allah rızası için kazaya kalan sabah namazının farzını kılmaya.</td></tr><tr><td>Öğle</td><td>Niyet ettim Allah rızası için kazaya kalan öğle namazının farzını kılmaya.</td></tr><tr><td>İkindi</td><td>Niyet ettim Allah rızası için kazaya kalan ikindi namazının farzını kılmaya.</td></tr><tr><td>Akşam</td><td>Niyet ettim Allah rızası için kazaya kalan akşam namazının farzını kılmaya.</td></tr><tr><td>Yatsı</td><td>Niyet ettim Allah rızası için kazaya kalan yatsı namazının farzını kılmaya.</td></tr><tr><td>Vitir</td><td>Niyet ettim Allah rızası için kazaya kalan vitir namazını kılmaya.</td></tr></tbody></table></div>
<p>Bu cümleler kolaylık sağlayan örneklerdir. Arapça söylemek veya kelimeleri birebir aynı kurmak şart değildir.</p>
<h2 id="bilinmeyen">Tarihi bilinmeyen çok sayıdaki kaza namazına niyet</h2><p>Yıllara yayılan namaz borcunda her namazın tarihini bilmek çoğu zaman mümkün değildir. Böyle bir durumda belirli bir vakit türünü sıraya koymak için “üzerimdeki ilk kazaya kalmış öğle namazının farzı” veya “son kazaya kalmış öğle namazının farzı” şeklinde niyet edilebilir. Aynı yöntemi diğer vakitlerde de sürdürebilirsiniz.</p>
<h2 id="kalp">Niyet kalpten mi, dille mi yapılır?</h2><p>Niyetin aslı kalbin yönelişidir. Kişi hangi namazı kıldığını biliyor ve onu kılmaya karar veriyorsa niyet gerçekleşir. Dille söylemek dikkati toplamak için yardımcı olabilir; ancak belirli bir kalıp cümle namazın bağımsız bir şartı değildir.</p>
<h2 id="yanlislar">Niyet konusunda sık karıştırılan noktalar</h2><ul><li>Aynı namaza hem sünnet hem kaza niyeti yapılmamalıdır.</li><li>Yalnızca “namaz kılmaya” demek yerine vaktin belirlenmesi daha açıktır.</li><li>Tarihi bilmiyorsanız tahminî tarih uydurmanız gerekmez; ilk veya son yaklaşımını kullanabilirsiniz.</li><li>Niyeti uzun ve karmaşık bir cümleye dönüştürmek gerekmez.</li></ul>
{box('Örnek','Bugün iki sabah kazası kılacaksanız her namazda ayrı niyet edin. İlkinde “ilk kazaya kalan sabah”, ikincisinde yine sıradaki ilk kazaya kalan sabah namazını kastetmiş olursunuz.','info')}
{faq([('Niyet etmeden kaza namazı kılınır mı?','Namazın hangi tür olduğu ve hangi vaktin kazası olduğuna yönelik niyet gerekir.'),('Niyet Türkçe yapılabilir mi?','Evet. Niyetin dili değil, kişinin neyi kılmaya yöneldiği önemlidir.'),('Tarihi hatırlamıyorsam niyet geçerli olur mu?','Evet. İlk veya son kazaya kalan belirli vakte niyet edilebilir.'),('Hem sünnet hem kaza niyeti yapılır mı?','Diyanet açıklamasına göre tek namaz hem kaza hem sünnet niyetiyle ikisini birden karşılamaz; namazın türü belirlenmelidir.')])}
{sources([('Diyanet: Kaza namazına nasıl niyet edilir?',SRC['niyet']),('Diyanet: Bir namaz hem kaza hem sünnet niyetiyle kılınabilir mi?',SRC['sunnet'])])}
'''

articles['kaza-namazi-kac-rekat']=f'''
{common_toc([('kisa','Kısa cevap'),('tablo','Rekât tablosu'),('gunluk','Günlük toplam'),('vitir','Vitir'),('sunnet','Sünnetler'),('ornek','Örnek hesaplar')])}
<h2 id="kisa">Kaza namazı kaç rekâttır? Kısa cevap</h2><p>Kaza namazının rekât sayısı, kazaya kalan farz namazın rekât sayısıyla aynıdır: sabah 2, öğle 4, ikindi 4, akşam 3 ve yatsı 4 rekâttır. Bu beş farzın bir günlük toplamı 17 rekâttır. Hanefî mezhebinde vitir de 3 rekât olarak ayrıca kaza edilir.</p>
<h2 id="tablo">Vakitlere göre rekât tablosu</h2><div class="table-wrap"><table><thead><tr><th>Namaz</th><th>Farz rekâtı</th><th>100 günlük borçta</th><th>1 yıllık yaklaşık borçta</th></tr></thead><tbody><tr><td>Sabah</td><td>2</td><td>200 rekât</td><td>730 rekât</td></tr><tr><td>Öğle</td><td>4</td><td>400 rekât</td><td>1.460 rekât</td></tr><tr><td>İkindi</td><td>4</td><td>400 rekât</td><td>1.460 rekât</td></tr><tr><td>Akşam</td><td>3</td><td>300 rekât</td><td>1.095 rekât</td></tr><tr><td>Yatsı</td><td>4</td><td>400 rekât</td><td>1.460 rekât</td></tr></tbody></table></div>
<h2 id="gunluk">Bir günlük kaza namazı toplamı kaç rekâttır?</h2><p>Beş farz namazın toplamı 17 rekâttır. Dolayısıyla yaklaşık 365 günlük bir borç, yalnızca farzlar üzerinden 6.205 rekâta karşılık gelir. Artık yıl, kişisel olarak kılınmış günler ve muafiyetler sonucu değiştirir.</p>
<div class="formula"><strong>Temel hesap:</strong> Eksik gün × 17 = farz rekât toplamı</div>
<h2 id="vitir">Vitir namazı hesaba dahil edilir mi?</h2><p>Hanefî mezhebinde vitir vacip kabul edilir ve kazası kılınır. Bu durumda her eksik gün için 3 rekât daha eklenir; günlük toplam 20 rekâta çıkar. Diğer mezheplerde vitrin hükmü farklı değerlendirildiğinden hesaplama aracında vitir seçimi kullanıcıya bırakılmıştır.</p>
<h2 id="sunnet">Sünnet namazlar kaza hesabına dahil edilir mi?</h2><p>Temel borç hesabına beş vakit namazın farzları dahil edilir. Diyanet açıklamasında, kılınmayan sünnetlerin genel olarak vakit çıktıktan sonra kaza edilmediği; aynı gün öğleden önce kaza edilen sabah namazının sünneti gibi özel bir istisna bulunduğu belirtilir.</p>
<h2 id="ornek">Örnek rekât hesapları</h2><div class="table-wrap"><table><thead><tr><th>Eksik süre</th><th>Yaklaşık gün</th><th>Farz vakit</th><th>Farz rekât</th></tr></thead><tbody><tr><td>1 yıl</td><td>365</td><td>1.825</td><td>6.205</td></tr><tr><td>5 yıl</td><td>1.826</td><td>9.130</td><td>31.042</td></tr><tr><td>10 yıl</td><td>3.652</td><td>18.260</td><td>62.084</td></tr><tr><td>20 yıl</td><td>7.305</td><td>36.525</td><td>124.185</td></tr></tbody></table></div>
{faq([('2 rekât kaza namazı hangisidir?','Sabah namazının farz kazası 2 rekâttır.'),('4 rekât kaza namazları hangileridir?','Öğle, ikindi ve yatsı namazlarının farz kazaları 4 rekâttır.'),('Akşam kazası kaç rekâttır?','Akşam namazının farz kazası 3 rekâttır.'),('Bir yıllık namaz borcu kaç rekâttır?','Beş farz üzerinden 365 gün için yaklaşık 6.205 rekâttır. Vitir ve kişisel düzeltmeler ayrı değerlendirilir.')])}
{sources([('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi']),('Diyanet: Kaza namazının delili',SRC['delil'])])}
'''

articles['kaza-namazi-nasil-hesaplanir']=f'''
{common_toc([('kisa','Kısa cevap'),('formul','Temel formül'),('baslangic','Başlangıç tarihi'),('dusulecek','Düşülecek günler'),('vakit','Vakit ve rekât hesabı'),('ornekler','Örnekler'),('belirsizlik','Belirsizlik')])}
<h2 id="kisa">Kaza namazı nasıl hesaplanır? Kısa cevap</h2><p>Kaza namazı hesabında önce namaz yükümlülüğünün başladığı tarih ile düzenli namaza başlanan tarih arasındaki toplam gün bulunur. Bu süreden namazların kılındığı günler ve dinen muaf olunan dönemler çıkarılır. Kalan gün, beş farz vakit için 5 ile; rekât için 17 ile çarpılır.</p>
<h2 id="formul">Kaza namazı hesaplama formülü</h2><div class="formula"><strong>Eksik gün =</strong> Toplam yükümlülük dönemi − namaz kılınan günler − muaf olunan günler</div><div class="formula"><strong>Toplam farz vakit =</strong> Eksik gün × 5</div><div class="formula"><strong>Toplam farz rekât =</strong> Eksik gün × 17</div>
<p>Bu formül planlama içindir. Kesin tarihler bilinmiyorsa sonuç tahminî olur. Vitir dahil edilirse Hanefî uygulamasında günlük 1 vakit ve 3 rekât daha eklenir.</p>
<h2 id="baslangic">Hesap hangi yaştan başlatılır?</h2><p>Namaz sorumluluğu buluğla başlar; bu başlangıç kişiden kişiye değişebilir. Kesin tarih biliniyorsa onu kullanın. Bilinmiyorsa aile bilgileri ve kişisel hatırlamalarla makul bir yaklaşık tarih belirleyin. Araçta yaştan çok tarih veya eksik gün/yıl üzerinden hesap yapmak daha şeffaf sonuç verir.</p>
<h2 id="dusulecek">Hesaptan hangi günler düşülür?</h2><ul><li>Düzenli namaz kılınan dönemler</li><li>Kısmen kılınan günlerde gerçekten eda edilen vakitler</li><li>Kadınlarda namaz yükümlülüğünün bulunmadığı hayız ve lohusalık günleri</li><li>Yanlışlıkla iki kez eklenmiş tarih aralıkları</li></ul>
<p>“Bir yıl boyunca bazen kıldım” gibi belirsiz dönemleri tamamen borç veya tamamen kılınmış saymak yerine ihtiyatlı bir oran kullanabilirsiniz. Örneğin haftada ortalama üç gün düzenli kıldığınızı hatırlıyorsanız bu dönemin yaklaşık yüzde 40–45’ini düşmek mümkündür; bunun yine tahmin olduğu belirtilmelidir.</p>
<h2 id="vakit">Vakit ve rekât hesabı</h2><div class="table-wrap"><table><thead><tr><th>Eksik gün</th><th>Beş farz vakit</th><th>Farz rekât</th></tr></thead><tbody><tr><td>30</td><td>150</td><td>510</td></tr><tr><td>365</td><td>1.825</td><td>6.205</td></tr><tr><td>1.000</td><td>5.000</td><td>17.000</td></tr><tr><td>3.652</td><td>18.260</td><td>62.084</td></tr></tbody></table></div>
<h2 id="ornekler">Üç örnek hesaplama</h2><h3>Örnek 1: 6 yıllık eksik dönem</h3><p>Yaklaşık 2.191 gün eder. Bu dönemde 200 gün namaz kılındığı biliniyorsa tahmini eksik gün 1.991 olur. Beş farz üzerinden yaklaşık 9.955 vakit hesaplanır.</p><h3>Örnek 2: Tarih aralığı</h3><p>1 Ocak 2018 ile 1 Ocak 2023 arasındaki dönem yaklaşık 1.826 gündür. Düzenli kılınan 300 gün düşülürse 1.526 eksik gün kalır.</p><h3>Örnek 3: Kadın kullanıcı</h3><p>Toplam 3.000 günlük dönemden namaz kılınan 400 gün ve hayız/lohusalık nedeniyle yükümlülük bulunmayan 500 gün çıkarılırsa tahmini eksik gün 2.100 olur.</p>
<h2 id="belirsizlik">Kesin tarih bilinmiyorsa ne yapılır?</h2><p>En erken ve en geç olası tarihlerle iki ayrı sonuç hesaplayın. Örneğin 8–10 yıl arası bir dönemden eminseniz alt sınır ve üst sınırı görün. Günlük planınızı üst sınıra göre kurup daha sonra hatırladığınız dönemleri düşebilirsiniz.</p>
{box('Hesaplama sonucu hüküm değildir','Araç, kullanıcının girdiği verilere göre matematiksel bir tahmin üretir. Namazın kişisel olarak borç olup olmadığı ve muafiyet günlerinin niteliği fıkhî bir değerlendirmedir.','warning')}
{faq([('Yaşa göre kaza namazı hesaplanır mı?','Evet; yükümlülüğün başladığı yaklaşık yaş ile düzenli namaza başlanan yaş arasındaki süre kullanılabilir. Tarih bilgisi varsa daha hassas sonuç verir.'),('Artık yıllar hesaba katılır mı?','Tarih aralığı yöntemi kullanıldığında gerçek gün sayısı hesaplanabilir. Yıl yönteminde ortalama 365,2425 gün kullanılması daha hassastır.'),('Kılınan bazı vakitler nasıl düşülür?','Gün bazında tam kılınan dönemleri düşürebilir; yalnızca bazı vakitlerin kılındığı dönemlerde vakit bazlı ayrı bir kayıt tutabilirsiniz.'),('Diyanet’in resmî hesaplama aracı var mı?','Bu site Diyanet’e ait değildir. Diyanet’in fetva içerikleri dinî çerçeve için kaynak olarak kullanılabilir; buradaki araç bağımsız bir planlama aracıdır.')])}
{sources([('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi']),('Diyanet: Kaza namazının delili',SRC['delil'])])}
'''

articles['kadinlar-icin-kaza-namazi-hesaplama']=f'''
{common_toc([('kisa','Kısa cevap'),('muafiyet','Muafiyet günleri'),('adet','Âdet günleri'),('lohusalik','Lohusalık'),('hesap','Adım adım hesap'),('ornek','Örnek'),('mezhep','Mezhep farkları')])}
<h2 id="kisa">Kadınlar için kaza namazı hesaplama: Kısa cevap</h2><p>Kadınlarda hesap yapılırken toplam yükümlülük döneminden namaz kılınan günlerin yanında hayız ve lohusalık nedeniyle namaz yükümlülüğünün bulunmadığı günler de çıkarılır. Bu günlerde kılınmayan namazlar kaza borcu sayılmaz. Düzensiz kanama ve istihâze gibi durumlar ise mezhebe göre ayrıca değerlendirilmelidir.</p>
<h2 id="muafiyet">Kadınlarda hangi günler hesaptan düşülür?</h2><ul><li>Gerçek hayız günleri</li><li>Lohusalık günleri</li><li>Namazların düzenli kılındığı günler</li><li>Kısmen kılınan dönemlerde eda edilen vakitler</li></ul>
<p>Otomatik olarak her ay aynı gün sayısını düşmek pratik olabilir ancak herkes için kesin sonuç vermez. Kişinin kendi döngü geçmişi, doğum sayısı ve lohusalık süreleri farklıdır.</p>
<h2 id="adet">Âdet günlerinde kılınmayan namazlar kaza edilir mi?</h2><p>Diyanet açıklamasına göre hayız ve lohusalık hâlinde namaz yükümlülüğü bulunmaz ve bu dönemlerde kılınmayan namazlar sonradan kaza edilmez. Bu nedenle kadınlara özel hesapta bu günler borçtan düşülmelidir.</p>
<h2 id="lohusalik">Lohusalık süresi nasıl hesaplanır?</h2><p>Her doğumdan sonraki fiilî lohusalık sürenizi mümkün olduğunca gerçekçi belirleyin. Azami süreyi otomatik olarak her doğuma uygulamak yerine kendi durumunuz esas alınmalıdır. Kanamanın türü ve süresi konusunda tereddüt varsa fıkhî ve tıbbi değerlendirme gerekebilir.</p>
<h2 id="hesap">Kadınlarda adım adım hesaplama</h2><ol><li>Namaz yükümlülüğünün başladığı tarihi yaklaşık olarak belirleyin.</li><li>Düzenli namaza başladığınız veya hesaplamanın bittiği tarihi seçin.</li><li>Toplam tarih aralığındaki günleri bulun.</li><li>Namaz kıldığınız günleri çıkarın.</li><li>Hayız günlerinin toplamını çıkarın.</li><li>Varsa lohusalık günlerini çıkarın.</li><li>Kalan günleri seçilen vakit sayısıyla çarpın.</li></ol>
<h2 id="ornek">Kadın kullanıcı için örnek hesap</h2><div class="table-wrap"><table><tbody><tr><th>Toplam dönem</th><td>3.652 gün</td></tr><tr><th>Namaz kılınan gün</th><td>500 gün</td></tr><tr><th>Hayız günleri</th><td>720 gün</td></tr><tr><th>Lohusalık günleri</th><td>60 gün</td></tr><tr><th>Tahmini eksik gün</th><td>2.372 gün</td></tr><tr><th>Beş farz vakit</th><td>11.860 vakit</td></tr></tbody></table></div>
<p>Bu yalnızca yöntemi gösteren örnektir. Aylık hayız süresi ve lohusalık kişiden kişiye değiştiği için kendi verilerinizi kullanmalısınız.</p>
<h2 id="mezhep">Düzensiz kanama ve mezhep farklılıkları</h2><p>Hayızın asgari ve azami süresi ile istihâze ayrımı mezheplere göre farklılık gösterebilir. Diyanet’in ilgili açıklamasında Hanefî ve Şâfiî ölçülerinin farklı olduğu belirtilir. Bu nedenle uzun veya düzensiz kanama dönemlerini otomatik olarak muafiyet saymak yerine mezhebinize göre değerlendirin.</p>
{box('Gizlilik','Hesaplama aracına girdiğiniz bilgiler tarayıcınızda işlenir. Kişisel döngü veya doğum bilgilerinizi bir hesap oluşturarak kaydetmeniz gerekmez.','info')}
{faq([('Âdet günlerinde namaz borcu oluşur mu?','Hayız döneminde namaz yükümlülüğü bulunmadığı için bu günlerde kılınmayan namazlar kaza edilmez.'),('Lohusalık günleri hesaplamadan düşülür mü?','Evet, namaz yükümlülüğünün bulunmadığı gerçek lohusalık günleri toplam dönemden düşülür.'),('Her ay 7 gün otomatik düşülebilir mi?','Bu yalnızca kaba bir tahmin olur. Daha doğru sonuç için kendi ortalama ve geçmiş bilgilerinizi kullanın.'),('Düzensiz kanamalarda ne yapılır?','Hayız ve istihâze ayrımı mezhepsel ve kişisel ayrıntı içerir. Yetkin bir din görevlisine danışın.')])}
{sources([('Diyanet: Âdet ve lohusalık hâllerinde ibadet',SRC['kadin']),('Diyanet: Hanefî ve Şâfiî mezhebinde kanama süreleri',SRC['adet'])])}
'''

articles['erkekler-icin-kaza-namazi-hesaplama']=f'''
{common_toc([('kisa','Kısa cevap'),('baslangic','Başlangıç yaşı'),('yontem','Hesaplama yöntemleri'),('ornek','Örnek hesap'),('plan','Bitirme planı'),('hatalar','Hatalar')])}
<h2 id="kisa">Erkekler için kaza namazı hesaplama: Kısa cevap</h2><p>Erkeklerde hesap, namaz sorumluluğunun başladığı dönem ile düzenli namaza başlanan tarih arasındaki eksik günlerin bulunmasına dayanır. Bu süreden namaz kılınan günler çıkarılır; kalan gün beş farz için 5, farz rekât toplamı için 17 ile çarpılır.</p>
<h2 id="baslangic">Hesaplama hangi yaştan başlar?</h2><p>Namaz yükümlülüğü buluğla başlar ve herkes için tek bir sabit yaş söylemek doğru değildir. Kesin başlangıç tarihini hatırlamıyorsanız kişisel gelişim döneminizi ve aile bilgisini kullanarak makul bir tarih belirleyebilirsiniz. İki olası tarih arasında kaldıysanız alt ve üst sınır hesaplamak daha şeffaftır.</p>
<h2 id="yontem">Üç hesaplama yöntemi</h2><div class="table-wrap"><table><thead><tr><th>Yöntem</th><th>Ne zaman kullanılır?</th><th>Avantajı</th></tr></thead><tbody><tr><td>Yıl sayısı</td><td>Yaklaşık süre biliniyorsa</td><td>Hızlıdır</td></tr><tr><td>Gün sayısı</td><td>Toplam eksik gün biliniyorsa</td><td>Doğrudan sonuç verir</td></tr><tr><td>Tarih aralığı</td><td>Başlangıç ve bitiş tarihi biliniyorsa</td><td>Artık yılları da içerir</td></tr></tbody></table></div>
<p>Arada namaz kıldığınız dönemler varsa bunları düşmeyi unutmayın. “On yıl hiç kılmadım” ile “on yıl düzensiz kıldım” aynı sonuç değildir.</p>
<h2 id="ornek">10 yıllık erkek kullanıcı örneği</h2><p>10 yıllık dönem yaklaşık 3.652 gündür. Bu dönemde yaklaşık 500 gün namazların düzenli kılındığı hatırlanıyorsa eksik gün 3.152 olur. Beş farz üzerinden yaklaşık 15.760 vakit ve 53.584 farz rekât hesaplanır.</p>
<h2 id="plan">Günlük hedefe göre bitirme planı</h2><div class="table-wrap"><table><thead><tr><th>Toplam 15.760 vakit için</th><th>Teorik süre</th></tr></thead><tbody><tr><td>Günde 1 vakit</td><td>Yaklaşık 43 yıl</td></tr><tr><td>Günde 5 vakit</td><td>Yaklaşık 8 yıl 8 ay</td></tr><tr><td>Günde 10 vakit</td><td>Yaklaşık 4 yıl 4 ay</td></tr><tr><td>Günde 20 vakit</td><td>Yaklaşık 2 yıl 2 ay</td></tr></tbody></table></div>
<p>Bu süreler ara verilmediği varsayımıyla teoriktir. Sürdürülebilirlik için günlük minimum ve haftalık hedefi birlikte belirlemek daha gerçekçi olabilir.</p>
<h2 id="hatalar">Hesapta sık yapılan hatalar</h2><ul><li>Buluğ başlangıcını herkes için aynı yaş kabul etmek.</li><li>Düzensiz de olsa namaz kılınan yılları tamamen borç saymak.</li><li>Farz rekât sayısıyla vakit sayısını karıştırmak.</li><li>Vitri mezhep tercihini belirtmeden otomatik eklemek.</li><li>Teorik bitiş tarihini kesin tarih gibi sunmak.</li></ul>
{faq([('Erkeklerde özel muafiyet günü var mı?','Kadınlardaki hayız ve lohusalık benzeri düzenli muafiyet dönemleri bulunmaz; ancak kişinin namaz sorumluluğunu etkileyen özel hâller ayrıca değerlendirilir.'),('Askerlik veya çalışma dönemleri borçtan düşülür mü?','Yalnızca namazların gerçekten kılındığı günler düşülür. Yoğunluk veya çalışma tek başına namaz borcunu kaldırmaz.'),('10 yıllık borç tam olarak 3.650 gün müdür?','Artık yıllar nedeniyle tarih aralığına göre 3.652 veya 3.653 gün olabilir. Araç ortalama veya gerçek tarih hesabı kullanır.'),('Vitir erkek hesabına dahil edilir mi?','Cinsiyete göre değil, mezhep yaklaşımına göre değerlendirilir. Hanefî kullanıcılar vitri ayrıca dahil edebilir.')])}
{sources([('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi']),('Diyanet: Kaza namazının delili',SRC['delil'])])}
'''

articles['kaza-namazi-cizelgesi']=f'''
{common_toc([('kisa','Kısa cevap'),('alanlar','Çizelge alanları'),('gunluk','Günlük çizelge'),('haftalik','Haftalık sistem'),('vakit','Vakit bazlı takip'),('yazdir','Yazdırma'),('motivasyon','Sürdürülebilirlik')])}
<h2 id="kisa">Kaza namazı çizelgesi nasıl hazırlanır? Kısa cevap</h2><p>Kaza namazı çizelgesinde başlangıç borcu, günlük hedef, tamamlanan sabah-öğle-ikindi-akşam-yatsı vakitleri ve kalan toplam yer almalıdır. Günlük işaretleme ayrıntı sağlar; haftalık toplam ise kaçırılan günlerde planın tamamen bozulmasını önler.</p>
<h2 id="alanlar">İyi bir takip çizelgesinde hangi alanlar olmalı?</h2><ul><li>Tarih</li><li>Günlük hedef</li><li>Sabah, öğle, ikindi, akşam ve yatsı için ayrı kutular</li><li>Vitir için isteğe bağlı alan</li><li>Günlük tamamlanan toplam</li><li>Kalan borç</li><li>Kısa not</li></ul>
<h2 id="gunluk">Günlük kaza namazı çizelgesi örneği</h2><div class="table-wrap"><table><thead><tr><th>Tarih</th><th>Hedef</th><th>Sabah</th><th>Öğle</th><th>İkindi</th><th>Akşam</th><th>Yatsı</th><th>Toplam</th></tr></thead><tbody><tr><td>1. gün</td><td>5</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>5</td></tr><tr><td>2. gün</td><td>5</td><td>✓</td><td>—</td><td>✓</td><td>✓</td><td>✓</td><td>4</td></tr></tbody></table></div>
<p>Çizelgede yalnızca “namaz kıldım” kutusu yerine hangi vaktin kazasının tamamlandığını ayrı göstermek, vakitler arasında dengesiz birikme oluşmasını önler.</p>
<h2 id="haftalik">Haftalık hedef sistemi</h2><p>Günde 5 vakit hedefleyen kişi için haftalık hedef 35 vakittir. Bir gün 3 vakitte kaldıysa ertesi gün 7 kılabilir; böylece tek bir aksama planı başarısız saydırmaz.</p><div class="formula"><strong>Haftalık hedef =</strong> Günlük hedef × 7</div>
<h2 id="vakit">Vakit bazlı mı, toplam sayı bazlı mı takip edilmeli?</h2><p>Toplam sayı motivasyon için kolaydır; vakit bazlı takip ise hangi namazın ne kadar kaldığını gösterir. En iyi sistem ikisini birlikte kullanır. Örneğin toplam 10 kaza tamamlanmış olsa bile bunların tamamı sabah namazıysa diğer vakitler değişmeden kalır.</p>
<h2 id="yazdir">Çizelgeyi yazdırma ve kullanma</h2><p>Sitedeki haftalık çizelgede hedef, tamamlanan ve not alanlarını doldurup “Takip Çizelgesini Yazdır” düğmesini kullanabilirsiniz. Yazdırma görünümünde yalnızca çizelge alanı yer alır. Fiziksel kopyayı namaz kıldığınız alana yakın tutmak düzeni hatırlatabilir.</p>
<h2 id="motivasyon">Çizelgeyi sürdürülebilir kılmak</h2><ul><li>İlk iki hafta düşük hedefle başlayın.</li><li>Her gün yerine haftalık başarı oranına bakın.</li><li>Yüzde 80 sürdürülen planı, üç gün sonra bırakılan çok yüksek plana tercih edin.</li><li>Her ay kalan toplamı güncelleyin.</li><li>Hastalık veya yoğunluk dönemlerinde hedefi geçici azaltın.</li></ul>
{faq([('Kaza namazı çizelgesi PDF olarak indirilebilir mi?','Mevcut çizelge tarayıcının yazdırma özelliğiyle PDF olarak kaydedilebilir. Yazdır ekranında hedef olarak “PDF’ye kaydet” seçeneğini kullanın.'),('Çizelgede rekât mı vakit mi takip edilmeli?','Vakit takibi genellikle daha kolaydır. Rekât toplamı bilgi amaçlı ayrıca gösterilebilir.'),('Her vaktin kazası eşit ilerlemeli mi?','Zorunlu bir eşitlik planı değildir; ancak vakit bazlı kayıt, bir namaz türünün geride kalmasını fark etmenizi sağlar.'),('Kaçırılan gün nasıl telafi edilir?','Bir sonraki güne aşırı yük bindirmek yerine haftalık hedef içinde dengeli biçimde telafi edebilirsiniz.')])}
{sources([('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi'])])}
'''

articles['kaza-namazi-bitirme-plani']=f'''
{common_toc([('kisa','Kısa cevap'),('formul','Plan formülü'),('hedef','Günlük hedef'),('modeller','Plan modelleri'),('ornek','10.000 vakit örneği'),('takip','Takip'),('zorlanma','Plan zor gelirse')])}
<h2 id="kisa">Kaza namazı bitirme planı: Kısa cevap</h2><p>Bitirme planı için toplam kaza vakti günlük hedefe bölünür. Örneğin 10.000 vakit borcu günde 5 vakitle teorik olarak 2.000 günde, günde 10 vakitle 1.000 günde tamamlanır. Gerçek bitiş tarihi ara verilen günlere göre uzayabilir.</p>
<h2 id="formul">Bitirme süresi nasıl hesaplanır?</h2><div class="formula"><strong>Tahmini gün =</strong> Toplam kalan vakit ÷ günlük kaza hedefi</div><p>Sonucu 365,2425’e bölerek yaklaşık yıl sayısını bulabilirsiniz. Hesaplama aracımız bu işlemi otomatik yapar ve tahmini bitiş tarihini gösterir.</p>
<h2 id="hedef">Günlük hedef nasıl seçilir?</h2><p>Hedefiniz mevcut farz namazları vaktinde kılmanızı, işinizi, sağlığınızı ve dinlenmenizi bozmamalıdır. İlk hafta deneyerek sürdürebildiğiniz sayıyı belirleyin. Planı ilerleyen aylarda yükseltmek, başta çok yüksek başlamaktan daha güvenlidir.</p>
<h2 id="modeller">Dört plan modeli</h2><div class="table-wrap"><table><thead><tr><th>Model</th><th>Günlük hedef</th><th>Uygulama</th></tr></thead><tbody><tr><td>Hafif</td><td>1</td><td>Yatsıdan sonra bir vakit</td></tr><tr><td>Dengeli</td><td>5</td><td>Her farzdan sonra bir vakit</td></tr><tr><td>Hızlı</td><td>10</td><td>Sabah 5, akşam 5</td></tr><tr><td>Esnek</td><td>Haftalık 35</td><td>Günlere değişken dağılım</td></tr></tbody></table></div>
<h2 id="ornek">10.000 vakit için bitirme süresi</h2><div class="table-wrap"><table><thead><tr><th>Günlük kaza</th><th>Teorik gün</th><th>Yaklaşık süre</th></tr></thead><tbody><tr><td>1</td><td>10.000</td><td>27 yıl 5 ay</td></tr><tr><td>5</td><td>2.000</td><td>5 yıl 5 ay</td></tr><tr><td>10</td><td>1.000</td><td>2 yıl 9 ay</td></tr><tr><td>20</td><td>500</td><td>1 yıl 4 ay</td></tr></tbody></table></div>
<h2 id="takip">İlerleme nasıl takip edilir?</h2><p>Her gün tamamlanan vakitleri çizelgeye işleyin. Haftanın sonunda toplamı kalan borçtan çıkarın. Aylık olarak günlük ortalamanızı hesaplayın; teorik bitiş tarihini gerçek ortalamaya göre yenileyin.</p>
<h2 id="zorlanma">Plan zor gelirse ne yapılmalı?</h2><ul><li>Günlük hedefi geçici olarak yarıya indirin.</li><li>Günlük yerine haftalık hedef kullanın.</li><li>Namazları iki kısa zaman bloğuna ayırın.</li><li>Biriken telafiyi tek güne yüklemeyin.</li><li>Mevcut farzların vaktinde kılınmasını birinci öncelik yapın.</li></ul>
{box('Gerçekçi beklenti','Uzun yıllara ait bir borcun birkaç hafta içinde kapanması çoğu kişi için mümkün değildir. İstikrarlı, ölçülebilir ve günlük hayatla uyumlu plan daha değerlidir.','info')}
{faq([('Günde kaç kaza namazı kılmalıyım?','Herkes için tek sayı yoktur. Gücünüze göre başlayıp sürdürülebilir bir günlük veya haftalık hedef belirleyin.'),('Günde 5 kaza kılarsam ne kadar sürer?','Toplam vakit sayınızı 5’e bölün. Örneğin 18.250 vakit yaklaşık 3.650 gün, yani yaklaşık 10 yıl sürer.'),('Bir gün planı kaçırırsam ne olur?','Plan matematiksel bir takiptir. Ertesi gün normale dönün veya haftalık hedef içinde kademeli telafi edin.'),('Bitirme tarihi kesin midir?','Hayır. Günlük ortalama, ara verilen günler ve başlangıç hesabındaki belirsizlik sonucu değiştirir.')])}
{sources([('Diyanet: Hangi namazlar kaza edilir?',SRC['hangi']),('Diyanet: Kaza namazı için uygun vakitler',SRC['vakit'])])}
'''

# preserve title/meta/intro but add rich html and FAQ schema data extraction manually from content is unnecessary.
pages=json.loads(DATA.read_text(encoding='utf-8'))
for p in pages:
    if p['slug'] in articles:
        p['content_html']=articles[p['slug']]
DATA.write_text(json.dumps(pages,ensure_ascii=False,indent=2),encoding='utf-8')
print('Updated',len(articles),'articles')
